### ISSUE TITLE
Broken for XML declaration and stuffs

### ISSUE THREAD

**Issue by itsjef** [htmlhint/brackets-htmlhint#11]
I am using Brackets 1.6 on Windows 10 64-bit, htmlhint version is the latest.

A normal, standard XML document opening should begin like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE myMessage [
    <!ELEMENT myMessage (#PCDATA)>
]>
...
```

However, it happens that I got all these error:

```
Special characters must be escaped : [ < ]. <?xml version="1.0" encoding="UTF-8"?>
Special characters must be escaped : [ > ]. <?xml version="1.0" encoding="UTF-8"?>
Special characters must be escaped : [ > ]. ]>
```

Makes me wonder if I declared my document wrongly myself or it's the linter that is :frowning: 
**Please fix.**

Meanwhile, I'll have to disable the plugin myself. :dash:

**Comment by cfjedimaster** [comment]
Why are you using HTMLHint to lint an XML doc?
