### ISSUE TITLE
Get an error

### ISSUE THREAD

**Issue by 1951FDG** [htmlhint/brackets-htmlhint#12]
HTMLHint terminated with error: SyntaxError: Unexpected token /

**Comment by cfjedimaster** [comment]
Can you share the document you were trying to lint?

**Comment by 1951FDG** [comment]
[#1](https://github.com/1951FDG/SixtyFour/blob/gh-pages/index.html)
[#2](https://github.com/1951FDG/SixtyFour/blob/gh-pages/processtimer.html)

Thanks for looking into this!

**Comment by cfjedimaster** [comment]
I'm sorry - but I can't reproduce this in the latest version of Brackets.

**Comment by 1951FDG** [comment]
are you testing with the the source version or brackets official extension version of brackets-htmlhint?

**Comment by cfjedimaster** [comment]
My local version - and it darn well better be the same. Checking.

**Comment by 1951FDG** [comment]
Both produce the same error, checked also using git version. Checked removing all extensions except this one, and removing config file.

**Comment by cfjedimaster** [comment]
Yep - it is. Can you try getting from here and copying it over?

**Comment by 1951FDG** [comment]
Tried the local version as well

Error in Developer Console:

`[CodeInspection] Provider HTMLHint (async) failed: SyntaxError: Unexpected token //language/CodeInspection.js:277`

**Comment by cfjedimaster** [comment]
What version of Brackets?

**Comment by 1951FDG** [comment]
I am troubleshooting now, it appears to be some config file is the culprit.

**Comment by 1951FDG** [comment]
.jshintrc is the problem regardless if .htmlhintrc is present or not. If I remove .jshintrc , the error is gone!

**Comment by cfjedimaster** [comment]
Is it a bad .jshintrc?

**Comment by 1951FDG** [comment]
That was it, it contained a comment, and JSON does not allow comments (should have known better)...

**Comment by cfjedimaster** [comment]
Woot. :) Well this was fun. ;)

**Comment by 1951FDG** [comment]
Strangely enough, nothing else was throwing errors, was kinda hard to catch, thanks for helping out :+1:
