### ISSUE TITLE
"defaultPreferences.json" Error: "xmlhint.options": }

### ISSUE THREAD

**Issue by ghost** [htmlhint/brackets-htmlhint#16]
"defaultPreferences.json" Error: Found a punctuator character '}' when expecting a quoteless string (check your syntax) at line 564,2 >>>	}

```json
	"wordWrap": true,

	"xmlhint.options":
	}            -> Error
}
```

not:

```json
	"wordWrap": true,

	"xmlhint.options": {
		"doctype-first": false
	}
}
```

in Source code:
```javascript
    var xmlpm = PreferencesManager.getExtensionPrefs("xmlhint");
    var xmlDefaults;
    xmlpm.definePreference("options", "object", {
        "doctype-first": false
    }).on("change", function () {
        xmlDefaults = xmlpm.get("options");
    });
```

------
@Brackets  Issues: https://github.com/adobe/brackets/issues/13230

**Comment by cfjedimaster** [comment]
I'm confused - where is defaultPreferences.json?

**Comment by hackseoer** [comment]
@cfjedimaster In the menu: Debug -> Open Preferences File

Windows 10: C:\Users\XXXX\AppData\Roaming\Brackets\defaultPreferences.json

> When debugging, this file can be deleted and the Brackets will regenerate the latest one.

**Comment by cfjedimaster** [comment]
So it sounds like the issue is with the preferences file - and it is correctly being reported, right?

**Comment by hackseoer** [comment]
https://github.com/cfjedimaster/brackets-htmlhint/blob/master/main.js#L19-L35
It is possible that because the HTML and XML `"doctype-first"` key names are repeated, you can try renaming it.

**Comment by cfjedimaster** [comment]
... I'm confused. The issue is a linting issue with a Brackets file. But what you pointed out in my file doesn't impact that. (afaik)
