### ISSUE TITLE
[Not A Bug] Feature to exclude angular templates

### ISSUE THREAD

**Issue by qbconcept** [htmlhint/brackets-htmlhint#17]
Would be nice to be able to add .htmlhintrc deeper in project structure so in main app linter still works but for angular template it will ignore some rules (like doctype).

**Comment by cfjedimaster** [comment]
Sure - I'd accept a PR on that.

**Comment by qbconcept** [comment]
Sorry for being completely numb...
...but this is approximately my 8th hour with github and maybe 24 hours since I've started learning to code.
By PR do you refer to 'Pull Request'? Isn't it something for people who actually know a little about programming stuff? :)

**Comment by cfjedimaster** [comment]
Ah yes - if you don't know how to code - don't worry about it. :) But if someone else sees this, they will know I'm ok with it.

**Comment by qbconcept** [comment]
Thought so. ;)
