### ISSUE TITLE
csslint support in html files

### ISSUE THREAD

**Issue by ghost** [htmlhint/brackets-htmlhint#6]
Adding the `"csslint": true` setting to a .htmlhintrc config file results in the following error:

`HTMLHint has timed out after waiting for 10000 ms`

I'm trying to get linting for CSS in the head tag of an html file; I'm working on an email template for mailchimp which needs everything to be a single file.

I have both this extension and [brackets-csslint](https://github.com/cfjedimaster/brackets-csslint) installed, which works correctly for .css files.

**Comment by cfjedimaster** [comment]
If you go to the web site, http://htmlhint.com/, paste in your text, and
enable csslint, does it fail there?

On Thu, Jan 8, 2015 at 5:13 PM, ajacombs-NZLS <notifications@github.com>
wrote:

> Adding the "csslint": true setting to a .htmlhintrc config file results
> in the following error:
>
> HTMLHint has timed out after waiting for 10000 ms
>
> I'm trying to get linting for CSS in the head tag of an html file; I'm
> working on an email template for mailchimp which needs everything to be a
> single file.
>
> I have both this extension and brackets-csslint
> <https://github.com/cfjedimaster/brackets-csslint> installed, which works
> correctly for .css files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-htmlhint/issues/6>.
>



-- 
===========================================================================
Raymond Camden, Web Standards Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by ajacombs-NZLS** [comment]
It works as expected, with errors in embedded css being picked up with the csslint option on, and not with it off.

**Comment by cfjedimaster** [comment]
So it looks like if you include CSSLint.js within the same context it is
*supposed* to work, but it fails to load w/ the latest version of CSSLint.
Not sure what to suggest here but open to suggestions.

On Fri, Jan 9, 2015 at 1:41 PM, ajacombs-NZLS <notifications@github.com>
wrote:

> It works as expected, with errors in embedded css being picked up with the
> csslint option on, and not with it off.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-htmlhint/issues/6#issuecomment-69387319>
> .
>



-- 
===========================================================================
Raymond Camden, Web Standards Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by Lichtjaeger** [comment]
You can't use `"csslint": true`. The correct form is something like `"csslint": {"doctype-first":false, ...}`.

I've started a PR with some improvements (.csslintrc and preference-file).

**Comment by Dawa12** [comment]
hey @Lichtjaeger, I was wondering if you write out the exact settings you have to enable inline css linting. Here is an image of my linting setting. Thanks!

![image](https://cloud.githubusercontent.com/assets/10649550/23801051/9c593074-057c-11e7-95bd-b474980098f8.png)

**Comment by Lichtjaeger** [comment]
Sorry, I switched to vs code. Can't answer any current brackets questions.

But what language is this? YAML? No comma, no brackets. My example was in JSON.

**Comment by Dawa12** [comment]
@Lichtjaeger this in my config.cson file in Atom. I put my customizations for all packages in there.

**Comment by cfjedimaster** [comment]
"Switched to vs code" - ditto. ;)
